apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  labels:
    app: devops-app
spec:
  replicas: 3  # Мы хотим 3 копии нашего приложения для отказоустойчивости
  selector:
    matchLabels:
      app: devops-app  # Этот деплоймент управляет подами с такой меткой
  template:
    metadata:
      labels:
        app: devops-app  # Метка, которую получат все созданные поды
    spec:
      containers:
        - name: app
          image: devops-app:v2  # Наш образ, который мы загрузили в kind!
          ports:
            - containerPort: 5000
          env:
            # Передаём настройки. DB_HOST указывает на имя Service базы данных (создадим его ниже)
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_NAME
              value: "appdb"
            - name: DB_USER
              value: "appuser"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets      # Имя Secret
                  key: db-password       # Ключ внутри Secret
            - name: WELCOME_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: WELCOME_MESSAGE
          # Проверка жизнеспособности (Liveness Probe)
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
