apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Не-секретные настройки, которые можно менять "на лету"
  WELCOME_MESSAGE: "🤖 Этот текст пришёл из ConfigMap! GitOps и K8s дружат!"
  APP_ENV: "production"
